### ISSUE TITLE
Option to open vifm as a sidebar a lá NERDtree

### ISSUE THREAD

**Issue by Pablo1107** [vifm/vifm.vim#19]
I don't know if it's possible in the current implementation. But as this plugin can be opened in the embedded terminal in Vim 8, can it be posible that the terminal launches in a split in the left side as if was a sidebar?

**Comment by xaizek** [comment]
It should be possible to add it as an option. Maybe more than one option, because neovim-vifm plugin has a variable for controlling width of the split.

**Comment by Pablo1107** [comment]
Nice, how can this be implemented?

**Comment by xaizek** [comment]
I would imagine that conditionally changing these `:enew` https://github.com/vifm/vifm.vim/blob/abf765c83f3d00c50d4fefac4bc8f869cff9aec0/plugin/vifm.vim#L95-L97 https://github.com/vifm/vifm.vim/blob/abf765c83f3d00c50d4fefac4bc8f869cff9aec0/plugin/vifm.vim#L124-L126 to `:vnew` like in neovim-vifm ([here](https://github.com/vifm/neovim-vifm/blob/7ff96352ebd4523d444bf7adb9fcbc6d9f1ed70b/plugin/vifm.vim#L121-L123)) would be a start. Also these lines (also two times):
```vim
buffer #
silent! bdelete! #
```
would need to close the window instead of switching to previous buffer.

**Comment by rbong** [comment]
This will be added by #22. You can open in a vertical split that's 40 columns wide with `:vertical 40Vifm` if `g:vifm_embed_term` is enabled or if you're using neovim.

**Comment by xaizek** [comment]
`g:vifm_embed_split` also needs to be enabled. And for opening on the left side regardless of Vim's options it should be:
```vim
:leftabove vertical 40Vifm
```

**Comment by xaizek** [comment]
Should work now as per comments above.
