### ISSUE TITLE
Netrw is opened after selection of file/folder in vim

### ISSUE THREAD

**Issue by pglira** [vifm/vifm.vim#40]
I'm using the vifm plugin for vim on several PCs - so far without any problems. However, today I installed the plugin on a new PC where a strange problem occurs. After `:EditVifm` vifm shows up. However, when I select a file or a folder vifm disappears and netrw is shown instead.

I've tried to set in my .vimrc:
`let g:vifm_replace_netrw = 1`
but that doesn' really help: sometimes vifm remains opened, sometimes netrw shows up again.

Any ideas what might be the issue?

I'm using vifm 0.10.1 and vim 8.0.

**Comment by xaizek** [comment]
You can try disabling `netrw` in `.vimrc` too. See [`:h netrw-noload`](https://vimhelp.org/pi_netrw.txt.html#netrw-noload). `vifm.vim` tries to do it, but essentially it's too late at that point because `netrw` is loaded before `vifm.vim`.

It seems to work even without disabling `netrw`, but there are cases when it doesn't. I guess something differs in your setup of Vim 8.0 and it doesn't work at all there. I don't remember seeing behaviour you describe, it could be that some changes in the plugin contribute to the issue.

**Comment by pglira** [comment]
Thank you for the quick reply. 

However, when I add
```
let g:loaded_netrw = 1
let g:loaded_netrwPlugin = 1
```
(as suggested in ``:h netrw-noload``) to my vimrc this appears when I select a folder in vifm:
![image](https://user-images.githubusercontent.com/14214284/79255260-449bcc80-7e86-11ea-8ddf-108d2ab8699c.png)
So it seems that vifm returns the folder to vim instead of entering the folder.

**Comment by xaizek** [comment]
Is the directory selected when you're trying to enter it in vifm?

**Comment by pglira** [comment]
No, it is not selected. I just tried to enter a directory to select a file. I tried both, the l and the enter key.

**Comment by xaizek** [comment]
Are you using vifm 0.10.1 or a build from `master` branch?

**Comment by pglira** [comment]
You're right. I compiled the master branch yesterday. It's working now with the source code release from the website. Thank you for your help!

**Comment by xaizek** [comment]
And thank you for the bug report, I didn't know it's broken until you've filed the issue. It's fixed now.
