### ISSUE TITLE
Doesn't work with vifm 0.7.8

### ISSUE THREAD

**Issue by normen** [vifm/vifm.vim#41]
Apparently the plugin doesn't support older versions of VIFM.

When I try to open VIFM version 0.7.8 in VIM through the plugin I get the following errror:
`got non-zero code from vifm: 1`

I do see that the "usage" page of vifm is displayed shortly so I suppose theres an issue with the command line parameters.

Obviously I could just update VIFM but I am running this instance on a web server where I can't just update the OS or install external packages.

Cheers,
Normen

**Comment by xaizek** [comment]
Practically it supports those versions which have corresponding features, but a couple of times there were some significant changes in how Vifm is invoked. You should be able to use `v0.7.8` tag from this repository, that's why those tags are there (I didn't realize that older ones weren't published, so pushed them now).

**Comment by normen** [comment]
Cool, thanks!
