### ISSUE TITLE
"Bad file description" "Press Return to continue"

### ISSUE THREAD

**Issue by c02y** [vifm/vifm.vim#6]
I tried to cp files/directories to another place use yy and p, or gUU command to to rename the current file/directory, it will pop a window every time saying 

    Background Process Error
    cp (or mv): write error: Bad file descriptor
    Press Return to continue

After pressing Enter key, it will execute the command of cp or mv, but window is annoying.

FYI:
vifm
Version: 0.8.1a
Git info: v0.8.1a-31-g7d52713ef236-dirty
compiled from the git source code: ./configure --prefix=/usr; make; make install

Ubuntu 14.04 32-bit
and
CentOS 6.5 32-bit

**Comment by xaizek** [comment]
This happens only if you run vifm from the plugin? In vim only or also in gvim?

You can switch to implementation with system calls (`set syscalls`), which should remove the error, but it looks strange, as if one of standard streams (stdin/stdout/stderr) is closed.

**Comment by c02y** [comment]
I just run it in terminal,  didn't try it in vim or gvim.

**Comment by xaizek** [comment]
> I just run it in terminal, didn't try it in vim or gvim.

OK, you just created an issue in the repository of the plugin, hence the question.

What terminal and shell are you using?

**Comment by c02y** [comment]
It seems I made a mistake, this issue should be under https://github.com/vifm/vifm/issues, not vifm.vim, sorry about that.

Terminal: Konsole/Xfce4-terminal
with fish-shell and tmux.

**Comment by xaizek** [comment]
Please check whether latest master (vifm/vifm@19473f2) fixes the issue.

My guess is that either by default or with some plugin/setting fish uses aliases/functions for cp/mv with `-v` (verbose) flag on and they try to print what's happening, but due to incorrect flags command output was pointing to read-only /dev/null and printing failed. (I simulated similar situation and got the error, but guessing about what's actually going on on your machine.)

**Comment by c02y** [comment]
Yes, it did fix that. Thanks.

**Comment by xaizek** [comment]
Great, thanks for testing.
