### ISSUE TITLE
Buffer with this name already exists

### ISSUE THREAD

**Issue by AckslD** [vifm/vifm.vim#66]
I sometimes get the following error:
```
Error detected while processing function <SNR>48_StartVifm:
line   87:
E95: Buffer with this name already exists
```
but then vifm opens normally anyway. Anyone else have the same issue or know why it happens?

**Comment by xaizek** [comment]
Looks like neovim (but not Vim) doesn't allow multiple terminal buffers with identical name, you get the message when you try to open second Vifm buffer.

Buffer name matters only if you see it (default one is long an ugly), maybe should append something like `(1)` to avoid name clashes.

**Comment by xaizek** [comment]
It happened only in Neovim because that part of the code runs only in Neovim.  The plugin appends suffixes now.

@infinitewhileloop Not sure if that's the same issue, your steps don't work for me, but it might be due to a different Neovim version.  Please open a new issue if it's still not fixed for you.
